### ISSUE TITLE
LaunchError

### ISSUE THREAD

**Issue by jordrow** [koszullab/GRAAL#7]
I am getting an error when running GRAAL saying "cuLaunchKernel failed: too many resources requested for launch". The full message is as follows:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "main_window.py", line 427, in run
    gl_window.start_EM()
  File "/home/GRAAL/main_gl.py", line 215, in start_EM
    self.simulation.sampler.modify_gl_cuda_buffer(0, self.dt)
  File "/home/GRAAL/cuda_lib_gl.py", line 1749, in modify_gl_cuda_buffer
    block=block_, grid=grid_)
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/driver.py", line 402, in function_call
    func._launch_kernel(grid, block, arg_buf, shared, None)
LaunchError: cuLaunchKernel failed: too many resources requested for launch

**Comment by rkoszul** [comment]
Hello,

Could you post your computer specs as well as the configuration you're working in (such as your OS, python version, CUDA version, NVIDIA driver version)? GRAAL can be fairly demanding when working on large genomes and it may be your configuration doesn't support it.
